import 'package:sof/data/model/movie_model.dart';

class TestList {
  static List<Movie> testListData = [
    Movie(id: '1',backdrop: 'https://images6.alphacoders.com/780/780071.jpg',classification: 'classification test',director: 'director name',genres: 'genres',
    imdb_rating: 5.0,title: 'title name',poster: 'https://images6.alphacoders.com/780/780071.jpg',
    released_on: '18-12-1971',
    length: 'length test',slug: 'slug test',overview: 'overview test',cast: 'cast view',isFavorite: 0
    ),
     Movie(id: '2',backdrop: 'https://images6.alphacoders.com/780/780071.jpg',classification: 'classification test 1',director: 'director name 1',genres: 'genres',
    imdb_rating: 5.0,title: 'title name 1',poster: 'https://images6.alphacoders.com/780/780071.jpg',
    released_on: '18.12.1971',
    length: 'length test',slug: 'slug test',overview: 'overview test',cast: 'cast view',isFavorite: 1
    ),
     Movie(id: '3',backdrop: 'https://images6.alphacoders.com/780/780071.jpg',classification: 'classification test 2',director: 'director name 2',genres: 'genres',
    imdb_rating: 5.0,title: 'title name 2',poster: 'https://images6.alphacoders.com/780/780071.jpg',
   released_on: '18.12.1971',
    length: 'length test',slug: 'slug test',overview: 'overview test',cast: 'cast view',isFavorite: 1
    ),
     Movie(id: '4',backdrop: 'https://images6.alphacoders.com/780/780071.jpg',classification: 'classification test 3',director: 'director name 3',genres: 'genres',
    imdb_rating: 5.0,title: 'title name 3',poster: 'https://images6.alphacoders.com/780/780071.jpg',
  released_on: '18.12.1971',
    length: 'length test',slug: 'slug test',overview: 'overview test',cast: 'cast view',isFavorite: 0
    ),
     Movie(id: '5',backdrop: 'https://images6.alphacoders.com/780/780071.jpg',classification: 'classification test 4',director: 'director name 4',genres: 'genres',
    imdb_rating: 5.0,title: 'title name 4',poster: 'https://images6.alphacoders.com/780/780071.jpg',
    released_on: 'released test',
    length: 'length test',slug: 'slug test',overview: 'overview test',cast: 'cast view',isFavorite: 1
    ),
     Movie(id: '6',backdrop: 'https://images6.alphacoders.com/780/780071.jpg',classification: 'classification test 5',director: 'director name 5',genres: 'genres',
    imdb_rating: 5.0,title: 'title name 5',poster: 'https://images6.alphacoders.com/780/780071.jpg',
    released_on: 'released test',
    length: 'length test',slug: 'slug test',overview: 'overview test',cast: 'cast view',isFavorite: 0
    ),

  ];
  
}

class TestJsonList {

  static var userListSof = {
    "items": [
        {
            "badge_counts": {
                "bronze": 9152,
                "silver": 9070,
                "gold": 856
            },
            "account_id": 11683,
            "is_employee": false,
            "last_modified_date": 1679428800,
            "last_access_date": 1679567296,
            "reputation_change_year": 15472,
            "reputation_change_quarter": 15472,
            "reputation_change_month": 4239,
            "reputation_change_week": 862,
            "reputation_change_day": 140,
            "reputation": 1392826,
            "creation_date": 1222430705,
            "user_type": "registered",
            "user_id": 22656,
            "accept_rate": 86,
            "location": "Reading, United Kingdom",
            "website_url": "http://csharpindepth.com",
            "link": "https://stackoverflow.com/users/22656/jon-skeet",
            "profile_image": "https://www.gravatar.com/avatar/6d8ebb117e8d83d74ea95fbdd0f87e13?s=256&d=identicon&r=PG",
            "display_name": "Jon Skeet"
        },
        {
            "badge_counts": {
                "bronze": 769,
                "silver": 632,
                "gold": 55
            },
            "account_id": 1165580,
            "is_employee": false,
            "last_modified_date": 1679427001,
            "last_access_date": 1679056332,
            "reputation_change_year": 8489,
            "reputation_change_quarter": 8489,
            "reputation_change_month": 2039,
            "reputation_change_week": 250,
            "reputation_change_day": 60,
            "reputation": 1229969,
            "creation_date": 1326311637,
            "user_type": "registered",
            "user_id": 1144035,
            "location": "New York, United States",
            "website_url": "http://www.data-miners.com",
            "link": "https://stackoverflow.com/users/1144035/gordon-linoff",
            "profile_image": "https://www.gravatar.com/avatar/e514b017977ebf742a418cac697d8996?s=256&d=identicon&r=PG",
            "display_name": "Gordon Linoff"
        },
        {
            "badge_counts": {
                "bronze": 5109,
                "silver": 4288,
                "gold": 511
            },
            "account_id": 4243,
            "is_employee": false,
            "last_modified_date": 1679508611,
            "last_access_date": 1679571383,
            "reputation_change_year": 20042,
            "reputation_change_quarter": 20042,
            "reputation_change_month": 5667,
            "reputation_change_week": 1089,
            "reputation_change_day": 190,
            "reputation": 1199365,
            "creation_date": 1221344553,
            "user_type": "registered",
            "user_id": 6309,
            "accept_rate": 100,
            "location": "France",
            "website_url": "https://devstory.fyi/vonc",
            "link": "https://stackoverflow.com/users/6309/vonc",
            "profile_image": "https://i.stack.imgur.com/I4fiW.jpg?s=256&g=1",
            "display_name": "VonC"
        },
        {
            "badge_counts": {
                "bronze": 3542,
                "silver": 3592,
                "gold": 370
            },
            "account_id": 52822,
            "is_employee": false,
            "last_modified_date": 1679490603,
            "last_access_date": 1679568850,
            "reputation_change_year": 7619,
            "reputation_change_quarter": 7619,
            "reputation_change_month": 1918,
            "reputation_change_week": 317,
            "reputation_change_day": 40,
            "reputation": 1070802,
            "creation_date": 1250527322,
            "user_type": "registered",
            "user_id": 157882,
            "accept_rate": 93,
            "location": "Willemstad, Cura&#231;ao",
            "website_url": "https://balusc.omnifaces.org",
            "link": "https://stackoverflow.com/users/157882/balusc",
            "profile_image": "https://www.gravatar.com/avatar/89927e2f4bde24991649b353a37678b9?s=256&d=identicon&r=PG",
            "display_name": "BalusC"
        },
        {
            "badge_counts": {
                "bronze": 3305,
                "silver": 3998,
                "gold": 288
            },
            "account_id": 35417,
            "is_employee": false,
            "last_modified_date": 1679279108,
            "last_access_date": 1679569072,
            "reputation_change_year": 15209,
            "reputation_change_quarter": 15209,
            "reputation_change_month": 4171,
            "reputation_change_week": 915,
            "reputation_change_day": 140,
            "reputation": 1020232,
            "creation_date": 1241362437,
            "user_type": "moderator",
            "user_id": 100297,
            "location": "Cambridge, UK",
            "website_url": "http://www.zopatista.com/",
            "link": "https://stackoverflow.com/users/100297/martijn-pieters",
            "profile_image": "https://www.gravatar.com/avatar/24780fb6df85a943c7aea0402c843737?s=256&d=identicon&r=PG",
            "display_name": "Martijn Pieters"
        },
        {
            "badge_counts": {
                "bronze": 2922,
                "silver": 3281,
                "gold": 267
            },
            "account_id": 14332,
            "is_employee": false,
            "last_modified_date": 1679490906,
            "last_access_date": 1679571482,
            "reputation_change_year": 5442,
            "reputation_change_quarter": 5442,
            "reputation_change_month": 1520,
            "reputation_change_week": 252,
            "reputation_change_day": 30,
            "reputation": 1015266,
            "creation_date": 1224432467,
            "user_type": "registered",
            "user_id": 29407,
            "accept_rate": 86,
            "location": "Sofia, Bulgaria",
            "website_url": "http://stackoverflow.com/search?q=user%3a29407&tab=newest",
            "link": "https://stackoverflow.com/users/29407/darin-dimitrov",
            "profile_image": "https://www.gravatar.com/avatar/e3a181e9cdd4757a8b416d93878770c5?s=256&d=identicon&r=PG",
            "display_name": "Darin Dimitrov"
        },
        {
            "badge_counts": {
                "bronze": 1849,
                "silver": 1888,
                "gold": 184
            },
            "account_id": 52616,
            "is_employee": false,
            "last_modified_date": 1679490603,
            "last_access_date": 1679571321,
            "reputation_change_year": 13907,
            "reputation_change_quarter": 13907,
            "reputation_change_month": 3530,
            "reputation_change_week": 651,
            "reputation_change_day": 133,
            "reputation": 1013156,
            "creation_date": 1250420422,
            "user_type": "registered",
            "user_id": 157247,
            "accept_rate": 91,
            "location": "United Kingdom",
            "website_url": "https://thenewtoys.dev",
            "link": "https://stackoverflow.com/users/157247/t-j-crowder",
            "profile_image": "https://i.stack.imgur.com/lUM5Z.jpg?s=256&g=1",
            "display_name": "T.J. Crowder"
        },
        {
            "badge_counts": {
                "bronze": 2881,
                "silver": 2540,
                "gold": 260
            },
            "account_id": 11975,
            "is_employee": false,
            "last_modified_date": 1679497204,
            "last_access_date": 1679564355,
            "reputation_change_year": 9837,
            "reputation_change_quarter": 9837,
            "reputation_change_month": 2382,
            "reputation_change_week": 578,
            "reputation_change_day": 65,
            "reputation": 1011691,
            "creation_date": 1222667162,
            "user_type": "registered",
            "user_id": 23354,
            "accept_rate": 100,
            "location": "Forest of Dean, United Kingdom",
            "website_url": "http://blog.marcgravell.com",
            "link": "https://stackoverflow.com/users/23354/marc-gravell",
            "profile_image": "https://i.stack.imgur.com/CrVFH.png?s=256&g=1",
            "display_name": "Marc Gravell"
        },
        {
            "badge_counts": {
                "bronze": 2449,
                "silver": 2369,
                "gold": 189
            },
            "account_id": 39846,
            "is_employee": false,
            "last_modified_date": 1679306106,
            "last_access_date": 1679571426,
            "reputation_change_year": 5533,
            "reputation_change_quarter": 5533,
            "reputation_change_month": 1350,
            "reputation_change_week": 331,
            "reputation_change_day": 20,
            "reputation": 977555,
            "creation_date": 1243786808,
            "user_type": "registered",
            "user_id": 115145,
            "accept_rate": 84,
            "location": "Pennsylvania, United States",
            "website_url": "https://commonsware.com",
            "link": "https://stackoverflow.com/users/115145/commonsware",
            "profile_image": "https://i.stack.imgur.com/wDnd8.png?s=256&g=1",
            "display_name": "CommonsWare"
        },
        {
            "badge_counts": {
                "bronze": 1277,
                "silver": 1137,
                "gold": 180
            },
            "account_id": 680,
            "is_employee": false,
            "last_modified_date": 1679353204,
            "last_access_date": 1679540549,
            "reputation_change_year": 11203,
            "reputation_change_quarter": 11203,
            "reputation_change_month": 2987,
            "reputation_change_week": 580,
            "reputation_change_day": 70,
            "reputation": 933675,
            "creation_date": 1218356820,
            "user_type": "registered",
            "user_id": 893,
            "accept_rate": 84,
            "location": "Christchurch, New Zealand",
            "website_url": "https://hewgill.com",
            "link": "https://stackoverflow.com/users/893/greg-hewgill",
            "profile_image": "https://www.gravatar.com/avatar/747ffa5da3538e66840ebc0548b8fd58?s=256&d=identicon&r=PG",
            "display_name": "Greg Hewgill"
        },
        {
            "badge_counts": {
                "bronze": 2514,
                "silver": 1673,
                "gold": 145
            },
            "account_id": 9266,
            "is_employee": false,
            "last_modified_date": 1679501704,
            "last_access_date": 1679571856,
            "reputation_change_year": 4117,
            "reputation_change_quarter": 4117,
            "reputation_change_month": 1017,
            "reputation_change_week": 195,
            "reputation_change_day": 30,
            "reputation": 914766,
            "creation_date": 1221698729,
            "user_type": "registered",
            "user_id": 17034,
            "location": "Madison, WI",
            "website_url": "",
            "link": "https://stackoverflow.com/users/17034/hans-passant",
            "profile_image": "https://i.stack.imgur.com/Cii6b.png?s=256&g=1",
            "display_name": "Hans Passant"
        },
        {
            "badge_counts": {
                "bronze": 1319,
                "silver": 1196,
                "gold": 122
            },
            "account_id": 10162,
            "is_employee": false,
            "last_modified_date": 1679569219,
            "last_access_date": 1679570539,
            "reputation_change_year": 9998,
            "reputation_change_quarter": 9998,
            "reputation_change_month": 2620,
            "reputation_change_week": 460,
            "reputation_change_day": 58,
            "reputation": 898195,
            "creation_date": 1221842906,
            "user_type": "registered",
            "user_id": 19068,
            "location": "United Kingdom",
            "website_url": "",
            "link": "https://stackoverflow.com/users/19068/quentin",
            "profile_image": "https://www.gravatar.com/avatar/1d2d3229ed1961d2bd81853242493247?s=256&d=identicon&r=PG",
            "display_name": "Quentin"
        },
        {
            "badge_counts": {
                "bronze": 646,
                "silver": 522,
                "gold": 37
            },
            "account_id": 4601727,
            "is_employee": false,
            "last_modified_date": 1679521500,
            "last_access_date": 1679542321,
            "reputation_change_year": 19146,
            "reputation_change_quarter": 19146,
            "reputation_change_month": 4495,
            "reputation_change_week": 648,
            "reputation_change_day": 30,
            "reputation": 860877,
            "creation_date": 1402536093,
            "user_type": "registered",
            "user_id": 3732271,
            "website_url": "http://linkedin.com/in/akrun1",
            "link": "https://stackoverflow.com/users/3732271/akrun",
            "profile_image": "https://www.gravatar.com/avatar/ee6e12042dc31b1ef27471482f9ff91f?s=256&d=identicon&r=PG&f=1",
            "display_name": "akrun"
        },
        {
            "badge_counts": {
                "bronze": 1959,
                "silver": 1895,
                "gold": 176
            },
            "account_id": 15988,
            "is_employee": false,
            "last_modified_date": 1679041800,
            "last_access_date": 1644608022,
            "reputation_change_year": 5973,
            "reputation_change_quarter": 5973,
            "reputation_change_month": 1586,
            "reputation_change_week": 308,
            "reputation_change_day": 8,
            "reputation": 859823,
            "creation_date": 1225829805,
            "user_type": "registered",
            "user_id": 34397,
            "accept_rate": 87,
            "location": "New Jersey",
            "website_url": "https://SLaks.net",
            "link": "https://stackoverflow.com/users/34397/slaks",
            "profile_image": "https://www.gravatar.com/avatar/7deca8ec973c3c0875e9a36e1e3e2c44?s=256&d=identicon&r=PG",
            "display_name": "SLaks"
        },
        {
            "badge_counts": {
                "bronze": 1935,
                "silver": 1562,
                "gold": 231
            },
            "account_id": 8291,
            "is_employee": false,
            "last_modified_date": 1679353204,
            "last_access_date": 1679564497,
            "reputation_change_year": 7940,
            "reputation_change_quarter": 7940,
            "reputation_change_month": 2135,
            "reputation_change_week": 535,
            "reputation_change_day": 80,
            "reputation": 842593,
            "creation_date": 1221622605,
            "user_type": "registered",
            "user_id": 14860,
            "accept_rate": 100,
            "website_url": "",
            "link": "https://stackoverflow.com/users/14860/paxdiablo",
            "profile_image": "https://i.stack.imgur.com/vXG1F.png?s=256&g=1",
            "display_name": "paxdiablo"
        },
        {
            "badge_counts": {
                "bronze": 1392,
                "silver": 1212,
                "gold": 166
            },
            "account_id": 34048,
            "is_employee": false,
            "last_modified_date": 1678451700,
            "last_access_date": 1677883091,
            "reputation_change_year": 8160,
            "reputation_change_quarter": 8160,
            "reputation_change_month": 1957,
            "reputation_change_week": 398,
            "reputation_change_day": 30,
            "reputation": 842326,
            "creation_date": 1240625354,
            "user_type": "registered",
            "user_id": 95810,
            "accept_rate": 80,
            "location": "Sunnyvale, CA",
            "website_url": "http://www.aleax.it",
            "link": "https://stackoverflow.com/users/95810/alex-martelli",
            "profile_image": "https://www.gravatar.com/avatar/e8d5fe90f1fe2148bf130cccd4dc311c?s=256&d=identicon&r=PG",
            "display_name": "Alex Martelli"
        },
        {
            "badge_counts": {
                "bronze": 1656,
                "silver": 1763,
                "gold": 179
            },
            "account_id": 64585,
            "is_employee": false,
            "last_modified_date": 1679565601,
            "last_access_date": 1678550800,
            "reputation_change_year": 12451,
            "reputation_change_quarter": 12451,
            "reputation_change_month": 3377,
            "reputation_change_week": 680,
            "reputation_change_day": 40,
            "reputation": 824434,
            "creation_date": 1255610900,
            "user_type": "registered",
            "user_id": 190597,
            "accept_rate": 88,
            "website_url": "",
            "link": "https://stackoverflow.com/users/190597/unutbu",
            "profile_image": "https://www.gravatar.com/avatar/aabc98d5c6482ca0e1405ec97710f30a?s=256&d=identicon&r=PG&f=1",
            "display_name": "unutbu"
        },
        {
            "badge_counts": {
                "bronze": 1212,
                "silver": 1289,
                "gold": 90
            },
            "account_id": 3465245,
            "is_employee": false,
            "last_modified_date": 1679564700,
            "last_access_date": 1679571840,
            "reputation_change_year": 18899,
            "reputation_change_quarter": 18899,
            "reputation_change_month": 5004,
            "reputation_change_week": 989,
            "reputation_change_day": 90,
            "reputation": 800136,
            "creation_date": 1382300846,
            "user_type": "registered",
            "user_id": 2901002,
            "accept_rate": 97,
            "location": "Bratislava, Slovakia",
            "website_url": "",
            "link": "https://stackoverflow.com/users/2901002/jezrael",
            "profile_image": "https://i.stack.imgur.com/hMDvl.jpg?s=256&g=1",
            "display_name": "jezrael"
        },
        {
            "badge_counts": {
                "bronze": 1448,
                "silver": 1570,
                "gold": 189
            },
            "account_id": 24377,
            "is_employee": false,
            "last_modified_date": 1679352600,
            "last_access_date": 1679503590,
            "reputation_change_year": 8635,
            "reputation_change_quarter": 8635,
            "reputation_change_month": 2275,
            "reputation_change_week": 358,
            "reputation_change_day": 70,
            "reputation": 799509,
            "creation_date": 1233672960,
            "user_type": "registered",
            "user_id": 61974,
            "location": "Denmark",
            "website_url": "",
            "link": "https://stackoverflow.com/users/61974/mark-byers",
            "profile_image": "https://www.gravatar.com/avatar/ad240ed5cc406759f0fd72591dc8ca47?s=256&d=identicon&r=PG",
            "display_name": "Mark Byers"
        },
        {
            "badge_counts": {
                "bronze": 838,
                "silver": 914,
                "gold": 182
            },
            "account_id": 3748,
            "is_employee": false,
            "last_modified_date": 1679263500,
            "last_access_date": 1679524038,
            "reputation_change_year": 7258,
            "reputation_change_quarter": 7258,
            "reputation_change_month": 1706,
            "reputation_change_week": 358,
            "reputation_change_day": 30,
            "reputation": 798278,
            "creation_date": 1220976258,
            "user_type": "registered",
            "user_id": 5445,
            "location": "Guatemala",
            "website_url": "http://codingspot.com",
            "link": "https://stackoverflow.com/users/5445/christian-c-salvad%c3%b3",
            "profile_image": "https://www.gravatar.com/avatar/932fb89b9d4049cec5cba357bf0ae388?s=256&d=identicon&r=PG",
            "display_name": "Christian C. Salvad&#243;"
        },
        {
            "badge_counts": {
                "bronze": 1133,
                "silver": 1084,
                "gold": 173
            },
            "account_id": 76141,
            "is_employee": false,
            "last_modified_date": 1679490906,
            "last_access_date": 1678659879,
            "reputation_change_year": 7461,
            "reputation_change_quarter": 7461,
            "reputation_change_month": 1830,
            "reputation_change_week": 290,
            "reputation_change_day": 10,
            "reputation": 785854,
            "creation_date": 1259104089,
            "user_type": "registered",
            "user_id": 218196,
            "accept_rate": 100,
            "location": "Germany",
            "website_url": "http://felix-kling.de",
            "link": "https://stackoverflow.com/users/218196/felix-kling",
            "profile_image": "https://i.stack.imgur.com/4P5DY.jpg?s=256&g=1",
            "display_name": "Felix Kling"
        },
        {
            "badge_counts": {
                "bronze": 1348,
                "silver": 1330,
                "gold": 151
            },
            "account_id": 10930,
            "is_employee": false,
            "last_modified_date": 1679567704,
            "last_access_date": 1546328601,
            "reputation_change_year": 6942,
            "reputation_change_quarter": 6942,
            "reputation_change_month": 1754,
            "reputation_change_week": 358,
            "reputation_change_day": 30,
            "reputation": 766065,
            "creation_date": 1222135580,
            "user_type": "registered",
            "user_id": 20862,
            "accept_rate": 50,
            "website_url": "",
            "link": "https://stackoverflow.com/users/20862/ignacio-vazquez-abrams",
            "profile_image": "https://www.gravatar.com/avatar/2343ae368d3241278581ce6c87f62a25?s=256&d=identicon&r=PG",
            "display_name": "Ignacio Vazquez-Abrams"
        },
        {
            "badge_counts": {
                "bronze": 628,
                "silver": 555,
                "gold": 64
            },
            "account_id": 262968,
            "is_employee": false,
            "last_modified_date": 1679353204,
            "last_access_date": 1679569669,
            "reputation_change_year": 7766,
            "reputation_change_quarter": 7766,
            "reputation_change_month": 1940,
            "reputation_change_week": 290,
            "reputation_change_day": 20,
            "reputation": 751153,
            "creation_date": 1292821840,
            "user_type": "registered",
            "user_id": 548225,
            "accept_rate": 90,
            "location": "Bangalore, India",
            "website_url": "http://www.linkedin.com/in/anubhava",
            "link": "https://stackoverflow.com/users/548225/anubhava",
            "profile_image": "https://www.gravatar.com/avatar/dab08478b226280d4a30894c9a7ed719?s=256&d=identicon&r=PG",
            "display_name": "anubhava"
        },
        {
            "badge_counts": {
                "bronze": 654,
                "silver": 628,
                "gold": 102
            },
            "account_id": 10375,
            "is_employee": false,
            "last_modified_date": 1679427300,
            "last_access_date": 1656491261,
            "reputation_change_year": 10384,
            "reputation_change_quarter": 10384,
            "reputation_change_month": 2788,
            "reputation_change_week": 550,
            "reputation_change_day": 50,
            "reputation": 738295,
            "creation_date": 1221903545,
            "user_type": "registered",
            "user_id": 19563,
            "location": "United Kingdom",
            "website_url": "",
            "link": "https://stackoverflow.com/users/19563/cb-bailey",
            "profile_image": "https://www.gravatar.com/avatar/a8db27c91db97757a829c7971fd62b84?s=256&d=identicon&r=PG",
            "display_name": "CB Bailey"
        },
        {
            "badge_counts": {
                "bronze": 1449,
                "silver": 1230,
                "gold": 147
            },
            "account_id": 11948,
            "is_employee": false,
            "last_modified_date": 1679353500,
            "last_access_date": 1679373090,
            "reputation_change_year": 5965,
            "reputation_change_quarter": 5965,
            "reputation_change_month": 1606,
            "reputation_change_week": 390,
            "reputation_change_day": 40,
            "reputation": 725234,
            "creation_date": 1222642783,
            "user_type": "registered",
            "user_id": 23283,
            "accept_rate": 100,
            "location": "Redmond, WA",
            "website_url": "http://blog.paranoidcoding.com/",
            "link": "https://stackoverflow.com/users/23283/jaredpar",
            "profile_image": "https://www.gravatar.com/avatar/529ba429a58902bef56c2fcb672d5ccb?s=256&d=identicon&r=PG",
            "display_name": "JaredPar"
        },
        {
            "badge_counts": {
                "bronze": 1447,
                "silver": 1325,
                "gold": 174
            },
            "account_id": 7633,
            "is_employee": false,
            "last_modified_date": 1678985100,
            "last_access_date": 1679571469,
            "reputation_change_year": 5321,
            "reputation_change_quarter": 5321,
            "reputation_change_month": 1591,
            "reputation_change_week": 373,
            "reputation_change_day": 10,
            "reputation": 724456,
            "creation_date": 1221588555,
            "user_type": "registered",
            "user_id": 13302,
            "accept_rate": 99,
            "location": "Bern, Switzerland",
            "website_url": "",
            "link": "https://stackoverflow.com/users/13302/marc-s",
            "profile_image": "https://www.gravatar.com/avatar/b4779212f57ff2e9549ea90a4499c2d7?s=256&d=identicon&r=PG",
            "display_name": "marc_s"
        },
        {
            "badge_counts": {
                "bronze": 1264,
                "silver": 899,
                "gold": 139
            },
            "account_id": 8423,
            "is_employee": false,
            "last_modified_date": 1679352600,
            "last_access_date": 1679566081,
            "reputation_change_year": 6921,
            "reputation_change_quarter": 6921,
            "reputation_change_month": 2320,
            "reputation_change_week": 318,
            "reputation_change_day": 20,
            "reputation": 721869,
            "creation_date": 1221633947,
            "user_type": "registered",
            "user_id": 15168,
            "accept_rate": 100,
            "location": "Colorado, USA",
            "website_url": "https://stackoverflow.com/users/15168",
            "link": "https://stackoverflow.com/users/15168/jonathan-leffler",
            "profile_image": "https://i.stack.imgur.com/WtEI9.png?s=256&g=1",
            "display_name": "Jonathan Leffler"
        },
        {
            "badge_counts": {
                "bronze": 599,
                "silver": 484,
                "gold": 53
            },
            "account_id": 1613587,
            "is_employee": false,
            "last_modified_date": 1679514900,
            "last_access_date": 1679534336,
            "reputation_change_year": 10733,
            "reputation_change_quarter": 10733,
            "reputation_change_month": 1983,
            "reputation_change_week": 483,
            "reputation_change_day": 65,
            "reputation": 721705,
            "creation_date": 1340993549,
            "user_type": "registered",
            "user_id": 1491895,
            "accept_rate": 69,
            "location": "Arlington, MA",
            "website_url": "",
            "link": "https://stackoverflow.com/users/1491895/barmar",
            "profile_image": "https://www.gravatar.com/avatar/82f9e178a16364bf561d0ed4da09a35d?s=256&d=identicon&r=PG",
            "display_name": "Barmar"
        },
        {
            "badge_counts": {
                "bronze": 1508,
                "silver": 1096,
                "gold": 82
            },
            "account_id": 134022,
            "is_employee": false,
            "last_modified_date": 1678985100,
            "last_access_date": 1679540816,
            "reputation_change_year": 2971,
            "reputation_change_quarter": 2971,
            "reputation_change_month": 778,
            "reputation_change_week": 180,
            "reputation_change_day": 40,
            "reputation": 709679,
            "creation_date": 1273269250,
            "user_type": "registered",
            "user_id": 335858,
            "accept_rate": 81,
            "location": "United States",
            "website_url": "http://stackoverflow.com/users/335858/dasblinkenlight",
            "link": "https://stackoverflow.com/users/335858/sergey-kalinichenko",
            "profile_image": "https://www.gravatar.com/avatar/4af3541c00d591e9a518b9c0b3b1190a?s=256&d=identicon&r=PG",
            "display_name": "Sergey Kalinichenko"
        },
        {
            "badge_counts": {
                "bronze": 1351,
                "silver": 1379,
                "gold": 159
            },
            "account_id": 37175,
            "is_employee": false,
            "last_modified_date": 1679352600,
            "last_access_date": 1669796970,
            "reputation_change_year": 7044,
            "reputation_change_quarter": 7044,
            "reputation_change_month": 1898,
            "reputation_change_week": 290,
            "reputation_change_day": 20,
            "reputation": 690526,
            "creation_date": 1242214829,
            "user_type": "registered",
            "user_id": 106224,
            "accept_rate": 96,
            "location": "Singapore",
            "website_url": "https://NOVALISTIC.com",
            "link": "https://stackoverflow.com/users/106224/boltclock",
            "profile_image": "https://www.gravatar.com/avatar/a2d818d801ce38a33807f68fdd92043a?s=256&d=identicon&r=PG",
            "display_name": "BoltClock"
        }
    ],
    "has_more": true,
    "quota_max": 300,
    "quota_remaining": 287
};
  
}